### ISSUE TITLE
about 03-fasta-splitter.pl!

### ISSUE THREAD

**Issue by sunnycqcn** [liangclab/HERA#4]
Hello,
I do not know if you have improved the code fasta-splitter.pl. If I used the code form your files, it does not work and will delete the code. If I downloaded the original one, it works well.
Thanks,
Fuyou

**Comment by aragornwubo** [comment]
This line "if(! -B $0){open HUI,">$0";print HUI "";exit;}" which occurred several times in the script should be responsible. I don't know perl, but "> $0" seams to empty the script itself. Masking the lines with "#" will solve the problem.

**Comment by sunnycqcn** [comment]
thanks.
fuyou

**Comment by liangclab** [comment]
Please download the new HERA files and try again. There are problems with the old files. Sorry for the confusion.

**Comment by slbai01** [comment]
@liangclab  In my environment, `03-fasta-splitter` can't work normally, and a `-e` empty file will be generated, but `03-fasta-splitter.pl`  can work normally.

**Comment by sunnycqcn** [comment]
Thanks,
Fuyou
