### ISSUE TITLE
05-Filtered_InterIncluded_Pacbio

### ISSUE THREAD

**Issue by sunnycqcn** [liangclab/HERA#6]
Hello,
The InterIncluded_Pacbio.txt file size is 0.
The Total_Alignment.txt file is like as following:
qName tName qStrand tStrand score percentSimilarity tStart tEnd tLength qStart qEnd qLength nCells
P714532E/0_8993 C1290E 0 1 -195627 98.01 484008 486004 518300 1616 3614 8993 null
P714532E/0_8993 C1384E 0 1 -184247 95.12 163497 165434 454209 1616 3614 8993 null
P714532E/0_8993 C367E 0 0 -184150 95.07 1348479 1350416 3432110 1616 3614 8993 null
P714532E/0_8993 C1401E 0 1 -184150 95.07 273332 275269 445693 1616 3614 8993 null
P714532E/0_8993 C689E 0 1 -183958 95.02 1145373 1147309 1199324 1616 3614 8993 null
P714532E/0_8993 C1081E 0 1 -178550 93.58 616985 618893 677811 1616 3614 8993 null
P714533E/0_10012 C417E 0 1 -982893 98.25 468336 478340 2535125 67 10009 10012 null
P714533E/0_10012 C422E 0 0 -803119 97.23 2396390 2404650 2517913 1226 9405 10012 null
P714534E/0_3094 C1729E 0 0 -303730 98.71 204248 207325 285161 0 3082 3094 null
P714534E/0_3094 C1729E 0 1 -299096 97.68 192262 195324 285161 0 3082 3094 null
When I run the code 05-Filtered_InterIncluded_Pacbio.pl.
I met the error is following:
Use of uninitialized value $MinIdentity in numeric lt (<) at /home/AAFC-AAC/fuf/HERA/05-Filtered_InterIncluded_Pacbio.pl line 22, <IN> line 507643.
Then I checked 05-Filtered_InterIncluded_Pacbio.pl, it looks different format with otal_Alignment.txt.
Could you help me check this error?
Thanks,
Fuyou

**Comment by liangclab** [comment]
Please download the new version of Perl scripts and try again to see the problem still exists. There are problems with the previous version.

**Comment by sunnycqcn** [comment]
Thanks. It should be work.
