### ISSUE TITLE
InterIncluded_Pacbio.txt and PacbioAlignmentFiltered.txt - File size zero

### ISSUE THREAD

**Issue by chopra29** [liangclab/HERA#8]
For some reason, I cannot get anything filtered out in from the alignment files.

**Comment by liangclab** [comment]
Can you download the new HERA files and try again? there are problems in the old files.

**Comment by chopra29** [comment]
Thank you it is executing now. Very excited to run this pipeline hoping it will help us as well.

**Comment by liangclab** [comment]
Sorry for the confusion. The running of HERA might be complicated due to large data output in genome assembly process. Therefore, please let us know if you encouter any problems.
